from app.models.cliente import Clientes
from app.models.administrador import Administrador
from app.models.producto import Productos
from app.models.proveedor import Proveedores
from app.models.compra import Compras
from app.models.detalleCompra import DetalleCompras
from app.models.venta import Ventas
from app.models.detalleVenta import DetalleVentas
from app.models.carrito import Carritos